# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IssueTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftLint'
pod 'SnapKit'
pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject_Rx'
pod 'RxDataSources'
  target 'IssueTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IssueTrackerUITests' do
    # Pods for testing
  end

end
